		<div id="topbar">we współpracy z <a href="http://www.mozilla.org">mozilla foundation</a> i <a href="http://www.mozilla-europe.org/">mozilla europe</a></div>
		<a id="homelink" href="index.php">Strona główna</a>
		<div id="menu">
			<ul>
				<li><a href="index.php" class="current">Strona główna</a></li><li><a href="news.php">Nowości</a></li><li><a href="projekty.php">Projekty</a></li><li><a href="zespol.php">Zespół</a></li><li><a href="wsparcie.php">Wsparcie</a></li><li><a href="dlaprasy.php">Dla prasy</a></li><li><a href="kontakt.php">Kontakt</a></li>

			</ul>
		</div>