<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" type="text/css" href="aviary.css" title="Blue" />
	<link rel="alternate stylesheet" type="text/css" href="brown.css" title="Brown" />
	<script type="text/javascript" src="js/styleswitcher.js"></script>
