
		<div id="footer">
			<p>&copy; 2005 AviaryPL. Wszelkie prawa zastrzeżone. | Styl strony: <a href="javascript:setActiveStyleSheet('Blue')">Błękit</a>/<a href="javascript:setActiveStyleSheet('Brown')">Brąz</a></p>
			<p><span lang="en">Hosted by <a href="http://xmpp.pl">XMPP.pl</a></span> | <a href="http://validator.w3.org/check/referer">W3C XHTML 1.0</a> | <a href="http://jigsaw.w3.org/css-validator/">W3C CSS 2.1</a></p>
		</div>
	</div>
</body>
</html>
