// Firebird extensions
// generated from xml on Tuesday 04th November 2003 08:45:56 AM


var T = 0;
var extensions = [];

e[T] = new extension("AdBlock");
e[T].id = "adblock";
e[T].author = ["Henrik Aasted Sorensen"];
e[T].authorEmail = [""];
e[T].shortdesc = "Powerful advertisement blocking tool";
e[T].description = "<p>AdBlock allows the user to specify a number of filters, which removes unwantedimages based on their address. Filters are specified using the wildcard character(*) or regular expressions. Thus it's possible to control in some detail what isdisplayed.</p><p>Upon loading a page, AdBlock will scan through it and remove or hide the elementsthat matches the filters entered by the user. It doesn't prevent content from beingdownloaded, merely from being displayed. It's capable of removing both images andFlash animations.</p>";
e[T].homepage = "http://adblock.mozdev.org/";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "10";
e[T].installFile = "http://adblock.mozdev.org/adblock-firebird-0.3.xpi";
T++;

e[T] = new extension("Aggreg8");
e[T].id = "aggreg8";
e[T].author = ["Philip Andreas Roche"];
e[T].authorEmail = [""];
e[T].shortdesc = "Powerfull RSS feed aggregator";
e[T].description = "<p>Powerfull RSS feed aggregator.</p>";
e[T].homepage = "http://aggreg8.mozdev.org/";
e[T].version = "0.0.1";
e[T].updated = "";
e[T].size = "46";
e[T].installFile = "http://aggreg8.mozdev.org/aggreg8.xpi";
T++;

e[T] = new extension("All-in-One Gestures");
e[T].id = "aio";
e[T].author = ["Marc Boullet"];
e[T].authorEmail = ["boullet.marc@wanadoo.fr"];
e[T].shortdesc = "Amalgamtion of various popular gestures based extensions";
e[T].description = "<p>This extension includes mouse gestures with customization, rockernavigation, tab and history scrolling, and autoscrolling similar tothat in IE, all in a single package.</p>";
e[T].homepage = "http://perso.wanadoo.fr/marc.boullet/ext/extensions-en.html#vers08";
e[T].version = "0.8.1";
e[T].updated = "20030907";
e[T].size = "39";
e[T].installFile = "http://perso.wanadoo.fr/marc.boullet/ext/allinonegest08.xpi";
T++;

e[T] = new extension("Autocomplete Disabler");
e[T].id = "noautocomp";
e[T].author = ["Chris Neale"];
e[T].authorEmail = ["cdn@mozdev.org"];
e[T].shortdesc = "Disables form autocompletion in Firebird";
e[T].description = "<p>Disables form autocompletion in Firebird</p>";
e[T].homepage = "";
e[T].version = "0.0.0";
e[T].updated = "";
e[T].size = "2";
e[T].installFile = "http://downloads.mozdev.org/cdn/noautocomp/noautocomp.xpi";
T++;

e[T] = new extension("Autoform");
e[T].id = "autoform";
e[T].author = ["Michael Kessler"];
e[T].authorEmail = ["Michael.Kessler@team.bluewin.com"];
e[T].shortdesc = "Manipulates/Loads/Saves form data";
e[T].description = "<p>Aids webdevelopers to avoid the boring task to fill out forms while developing. The process of save and load form data can be automated and configured. The form data will be saved into the preferences to its context, which is calculated on the base URI, the form name and and a hash value over all form elements. So every page should have it's unique key where the values are stored</p>";
e[T].homepage = "http://autoform.mozdev.org/";
e[T].version = "0.31";
e[T].updated = "20031003";
e[T].size = "10";
e[T].installFile = "http://downloads.mozdev.org/autoform/autoform.xpi";
T++;

e[T] = new extension("Autohide Toolbox (True Fullscreen)");
e[T].id = "autohide";
e[T].author = ["Jochen"];
e[T].authorEmail = ["joe@krickelkrackel.de"];
e[T].shortdesc = "Auto-Hide FullScreen (a la IE)";
e[T].description = "<p>Hides the toolbars when entering full screen, and contains featureslike, A la IE floating, customizable static bars, etc.</p>";
e[T].homepage = "http://www.krickelkrackel.de/autohide.htm";
e[T].version = "0.6.8";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://www.krickelkrackel.de/autohide_exp.xpi";
T++;

e[T] = new extension("Autoscroll");
e[T].id = "autoscroll";
e[T].author = ["skidooer"];
e[T].authorEmail = [""];
e[T].shortdesc = "Have the page autoscroll when you click the middle mouse button";
e[T].description = "<p>AutoScroll is an addon for Firebird that emulates the autoscrolling functionality of InternetExplorer. For those unfamiliar with this, when you middle click on a page (typically by clickinga mouse wheel button) you can then move the mouse up and down to have the page scroll by youwithout further mouse movements.</p>";
e[T].homepage = "http://autoscroll.mozdev.org/";
e[T].version = "0.3.3";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://autoscroll.mozdev.org/autoscroll.xpi";
T++;

e[T] = new extension("BlockFall");
e[T].id = "blockfall";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "A Tetris clone that runs in Mozilla.";
e[T].description = "<p>BlockFall is a clone of the popular game Tetris.  It is playedusing the following keyboard commands:</p><ul>  <li>Up: rotate the current block clockwise</li>  <li>Left/Right/Down: move the current block lefct, right or down one row or column</li>  <li>'j': rotate the current block anticlockwise</li>  <li>'k': rotate the current block clockwise</li>  <li>'p': pause or unpause the game</li></ul><p>Start BlockFall by selecting \"Play BlockFall\" from the Tools menu.</p>";
e[T].homepage = "";
e[T].version = "0.3.1";
e[T].updated = "";
e[T].size = "10";
e[T].installFile = "http://downloads.mozdev.org/cdn/blockfall/blockfall.xpi";
T++;

e[T] = new extension("Bookmark Backup");
e[T].id = "bookmarkbackup";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Creates a backup of the bookmarks file each time Firebird is closed.";
e[T].description = "<p>An extremely basic extension that creates a backup of the bookmarks file each time Firebird is closed. The backups can be found in the Firebird profile directory. They will be named bookmarks.html.<day> e.g. bookmarks.html.sun, bookmarks.html.mon, bookmarks.html.tue, etc. If Firebird's bookmarks become corrupted or lost simply find the backup for the previous day and rename it to bookmarks.html (if necessary delete the corrupted version first).</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/";
e[T].version = "0.1.2";
e[T].updated = "";
e[T].size = "13";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/bookmarkbackup.xpi";
T++;

e[T] = new extension("Bookmark Links Checker");
e[T].id = "bookmarkchecker";
e[T].author = ["Torisugari"];
e[T].authorEmail = ["torisugari_moz@yahoo.co.jp"];
e[T].shortdesc = "Verifies whether your bookmarks are still valid.";
e[T].description = "<p>Bookmark Link Checker detects updated, redirected, and broken links in your bookmarks list.</p>";
e[T].homepage = "";
e[T].version = "0.5.0";
e[T].updated = "";
e[T].size = "21";
e[T].installFile = "http://cgi29.plala.or.jp/mozzarel/addon/firebird/linkchecker/linkchecker.xpi";
T++;

e[T] = new extension("BlogThis");
e[T].id = "blogthis";
e[T].author = ["Phil Ringnalda"];
e[T].authorEmail = [""];
e[T].shortdesc = "Context menu option to BlogThis with Blogger";
e[T].description = "<p>Adds a context menu option to blog a link to the current page and the selected text(if any) through Blogger's BlogThis form.</p>";
e[T].homepage = "http://philringnalda.com/mozilla/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://philringnalda.com/mozilla/blogthis.xpi";
T++;

e[T] = new extension("Browser Uptime");
e[T].id = "browseruptime";
e[T].author = ["Michael O'Rourke"];
e[T].authorEmail = ["momokatte@hotmail.com"];
e[T].shortdesc = "Shows you the uptime of a particular browser instance.";
e[T].description = "<ul>  <li>Adds a &quot;Browser Uptime&quot; option to the Tools menu.</li>  <li>Supports language locales (contains en-US).</li></ul>";
e[T].homepage = "http://www.cosmicat.com/software/uptime/";
e[T].version = "1.2";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://www.cosmicat.com/software/uptime/uptime.xpi";
T++;

e[T] = new extension("Bugxula");
e[T].id = "bugxula";
e[T].author = ["Myk Melez"];
e[T].authorEmail = ["myk@mozilla.org"];
e[T].shortdesc = "XUL client for Bugzilla installations.";
e[T].description = "<p>XUL client for Bugzilla installations. It aims to let you doeverything you can do with the current web-based interface toBugzilla and more with a rich user interface like that of adesktop or client-server application.</p>";
e[T].homepage = "http://bugxula.mozdev.org/";
e[T].version = "2003-06-20";
e[T].updated = "";
e[T].size = "48";
e[T].installFile = "http://downloads.mozdev.org/bugxula/bugxula-20030620.xpi";
T++;

e[T] = new extension("Cards");
e[T].id = "cards";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "A collection of patience/solitaire card games";
e[T].description = "<p>A collection of patience/solitaire card games including:</p><ul><li>Aces Up</li><li>Canfield</li><li>Double Solitaire</li><li>FreeCell</li><li>Grandfather</li><li>Gypsy</li><li>Klondike (like Windows Solitaire)</li><li>Mod 3</li><li>Regiment</li><li>Spider Solitaire</li><li>Yukon</li></ul><p>Feature autoplay, hints, infinite levels of undo, scoring, animationand intelligent moving of cards when you middle click on them.</p>";
e[T].homepage = "http://cardgames.mozdev.org/";
e[T].version = "0.10.3";
e[T].updated = "";
e[T].size = "74";
e[T].installFile = "http://downloads.mozdev.org/cardgames/cards.xpi";
T++;

e[T] = new extension("Calendar for Windows");
e[T].id = "calendar";
e[T].author = ["Mike Potter"];
e[T].authorEmail = [""];
e[T].shortdesc = "A calendar client application using Mozilla technologies";
e[T].description = "<p>A Calendar application written in XUL.</p><p>Versions for other OSs can be found at the <ahref=\"http://www.mozilla.org/projects/calendar/\">project homepage</a>.</p><p>Note: this application is buggy when run from Firebird, because it wascreated for the Mozilla Application Suite.  It does not appear in theExtension panel of the Options window, and does not add any menu items toaccess it.  To load it type <kbd>chrome://calendar/content/</kbd> in theurl bar, or start Firebird from the command line with the switch<kbd>-chrome chrome://calendar/content/</kbd>.</p>";
e[T].homepage = "http://www.mozilla.org/projects/calendar/";
e[T].version = "0.8";
e[T].updated = "";
e[T].size = "609";
e[T].installFile = "http://www.oeone.com/files/calendar_windows.xpi";
T++;

e[T] = new extension("Calendar Opener");
e[T].id = "quicktoolsopencalendar";
e[T].author = ["Biju G. C"];
e[T].authorEmail = [""];
e[T].shortdesc = "Creates menuitem to open the calendar extension";
e[T].description = "<p>This extension creates a \"Calendar\" menuitem in the \"Tools\" menu, which will allow you to open Calendar, once you also install the <a  href=\"http://www.mozilla.org/projects/calendar/\">Calendar extension</a>.</p>";
e[T].homepage = "http://quicktools.mozdev.org/";
e[T].version = "2003.1029.0";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://downloads.mozdev.org/quicktools/QuickToolsOpenCalendar.xpi";
T++;

e[T] = new extension("Chatzilla");
e[T].id = "chatzilla";
e[T].author = ["Robert Ginda"];
e[T].authorEmail = [""];
e[T].shortdesc = "Customizable IRC client";
e[T].description = "<p>ChatZilla is an IRC client that is written entirely in JavaScript and XUL</p>";
e[T].homepage = "http://www.hacksrus.com/~ginda/chatzilla/";
e[T].version = "0.9.36";
e[T].updated = "";
e[T].size = "148";
e[T].installFile = "http://www.hacksrus.com/~ginda/chatzilla/chatzilla-0.9.36.xpi";
T++;

e[T] = new extension("Checky");
e[T].id = "checky";
e[T].author = ["Joachim Schreiber"];
e[T].authorEmail = ["yo@yos.biz"];
e[T].shortdesc = "Interface to online validaton and analysis services";
e[T].description = "<p>A simple interface for web content and resource developersto free and commercial online validaton and analysis services.</p><p>With Checky you can setup, combine, and use 18 different onlinevalidation and checking services. Simply choose your services withChecky-Agent, browse to a web resource and press F10 to display theresults of the selected services in a new browser tab or window.</p>";
e[T].homepage = "http://checky.mozdev.org/";
e[T].version = "2.0";
e[T].updated = "";
e[T].size = "123";
e[T].installFile = "http://osdn.dl.sourceforge.net/sourceforge/checky/checky-2.0.xpi";
T++;

e[T] = new extension("ChromEdit");
e[T].id = "chromedit";
e[T].author = ["Chris Neale"];
e[T].authorEmail = ["cdn@mozdev.org"];
e[T].shortdesc = "Provides a means of editing the user files.";
e[T].description = "<p>Provides a means of editing the user files, i.e. userChrome.css, userContent.css, user.js without the need to find the profile directory.</p><p>0.0.3 brings an autosave feature should you edit and neglect to save yourself.</p>";
e[T].homepage = "http://cdn.mozdev.org/";
e[T].version = "0.0.4.5";
e[T].updated = "";
e[T].size = "30";
e[T].installFile = "http://downloads.mozdev.org/cdn/chromedit/chromedit.xpi";
T++;

e[T] = new extension("Clone Window");
e[T].id = "clonewindow";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Clones the current tab's address and history into the new window when the New Window command is used.";
e[T].description = "<p>Clones the current tab's address and history into the new window when the New Window command is used.</p><p>If installed, Optimoz Mouse Gestures' Duplicate Window gesture is overridden by Clone Window's own version.</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/#cw";
e[T].version = "0.1.2";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/clonewindow.xpi";
T++;

e[T] = new extension("Compact Menu");
e[T].id = "compactmenu";
e[T].author = ["Chris Neale"];
e[T].authorEmail = ["cdn@mozdev.org"];
e[T].shortdesc = "Allow you to customise the menubar as is, and adds a button alternative.";
e[T].description = "<p>Customiser for the menubar, which lets you cut the menubardown to the menus you use, and even reduce the space it takes upto a single menu button.</p>";
e[T].homepage = "http://cdn.mozdev.org/compact/";
e[T].version = "1.5.1";
e[T].updated = "";
e[T].size = "17";
e[T].installFile = "http://downloads.mozdev.org/cdn/compact/compact.xpi";
T++;

e[T] = new extension("Copy Image");
e[T].id = "copyimage";
e[T].author = ["Jordan Callicoat"];
e[T].authorEmail = [""];
e[T].shortdesc = "Activates the inherent ability to copy images to the clipboard.";
e[T].description = "<p>Adds a 'Copy Image to Clipboard' item to the context menu,below the 'Copy Image Location' item.</p>";
e[T].homepage = "http://gratisdei.com/FB.htm";
e[T].version = "";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://extensionroom.mozdev.org/install.php/http://gratisdei.com/copyimage.xpi";
T++;

e[T] = new extension("CTC");
e[T].id = "ctc";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Adds 'Close Tab' to the context menu for webpages";
e[T].description = "<p>Adds 'Close Tab' to the context menu for webpages below 'Stop'.The item is hidden when only one tab is open.</p>";
e[T].homepage = "";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "2";
e[T].installFile = "http://downloads.mozdev.org/cdn/ctc/ctc.xpi";
T++;

e[T] = new extension("Deepest Sender");
e[T].id = "deepestsender";
e[T].author = ["David Murray"];
e[T].authorEmail = ["lid2000@tpg.com.au"];
e[T].shortdesc = "LiveJournal blogging";
e[T].description = "<p>Deepest Sender (it's an anagram) will hopefully end up being theLiveJournal client I always wanted. The UI is primarily based on theVisions (the default one) Win32 LiveJournal client, but it lives insideMozilla. Response sorting, saving and password functions have beenlifted from the LiveLizard project.</p>";
e[T].homepage = "http://deepestsender.mozdev.org/";
e[T].version = "2.6";
e[T].updated = "";
e[T].size = "94";
e[T].installFile = "http://downloads.us-east3.mozdev.org/deepestsender/deepestsender.xpi";
T++;

e[T] = new extension("Digger");
e[T].id = "digger";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Adds useful site navigation tools to a context menu to the Go button";
e[T].description = "<p>Aimed at power surfers. It adds a context menu to the Go buttonon the toolbar with several useful functions:</p><ul><li>clearing the address bar (for Linux users)</li><li>navigating to parent directories in URLs</li><li>switching to the ftp equivalent of an http site or vice versa</li><li>climbing up through subdomains, e.g. get to http://example.com/  from http://sub.example.com/</li></ul><p>It also makes middle-clicking the Go button open the current urlin a new tab - useful for duplicating your current tab.</p><p>Digger was originally based on the Diggler extension.  Thanks toAdam Lock for the idea.</p>";
e[T].homepage = "";
e[T].version = "0.5.5";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://downloads.mozdev.org/cdn/digger/digger.xpi";
T++;

e[T] = new extension("Diggler");
e[T].id = "diggler";
e[T].author = ["Adam Lock"];
e[T].authorEmail = ["adamlock@eircom.net"];
e[T].shortdesc = "A button for clearing the location bar and navigating nested sites";
e[T].description = "<p>Diggler is a small but powerful add-on for Mozilla, Netscape and Firebird.It adds a button next to the location bar which can clear the location bar(much like the one in Konqueror) but also drops down a menu with some usefulactions such as being able to disable popup windows and navigate to parentdirectories in URLs (handy for FTP operations and nested sites). Diggler isa very useful convenience for power surfers. Take a look at the <ahref=\"http://diggler.mozdev.org/screenshots.html\">screenshots</a> and you'llsee what it does.</p>";
e[T].homepage = "http://diggler.mozdev.org/";
e[T].version = "0.6";
e[T].updated = "";
e[T].size = "8";
e[T].installFile = "http://diggler.mozdev.org/diggler-0.6.xpi";
T++;

e[T] = new extension("Download Statusbar");
e[T].id = "downloadstatus";
e[T].author = ["Devon Jensen"];
e[T].authorEmail = ["velcrospud@hotmail.com"];
e[T].shortdesc = "Track downloads in a hide-away status bar.";
e[T].description = "<p>Allows you to keep track of ongoing and completed downloadsin an easy to use, hide-away statusbar.</p>";
e[T].homepage = "http://downloadstatusbar.mozdev.org/";
e[T].version = "0.8";
e[T].updated = "20030526";
e[T].size = "18";
e[T].installFile = "http://downloads.mozdev.org/downloadstatusbar/downbar/downbar.xpi";
T++;

e[T] = new extension("Download Sort");
e[T].id = "downsort";
e[T].author = ["Devon Jensen"];
e[T].authorEmail = ["velcrospud@hotmail.com"];
e[T].shortdesc = "Automatically save downloads to specific folders based on the file type";
e[T].description = "<p>This extension allows you to automatically send downloads to specific foldersdepending on the file extension.  Also, you can specify what to do if there isalready a file of that name in the folder:  Prompt for a new filename, incrementthe filename, or cancel the download.</p><p>Update:</p><p>Compatible with Firebird 0.7 and nightlies later that July 25th (not backwards compatible);   Added alternate date format, choose between mm.dd.yyyy or yyyy.mm.dd;   Fixed permissions on folders created in linux</p>";
e[T].homepage = "http://downloadstatusbar.mozdev.org/downsort/";
e[T].version = "2.01";
e[T].updated = "";
e[T].size = "19";
e[T].installFile = "http://downloads.mozdev.org/downloadstatusbar/downsort/downsort.xpi";
T++;

e[T] = new extension("easyGestures");
e[T].id = "easygestures";
e[T].author = ["Snow Blanc"];
e[T].authorEmail = [""];
e[T].shortdesc = "Simplified modification of Radial Context";
e[T].description = "<p>EasyGestures is a simplified and revamped modification of the original radialContext extension. It combines mouse gestures with a circular UI. It has a firebird-like theme and all the actions are customizable in the preferences dialog. Enjoy folks !</p>";
e[T].homepage = "http://easygestures.mozdev.org/";
e[T].version = "2.1.0";
e[T].updated = "";
e[T].size = "438";
e[T].installFile = "http://downloads.mozdev.org/easygestures/easyGestures.xpi";
T++;

e[T] = new extension("EditCSS");
e[T].id = "editcss";
e[T].author = ["Pascal Guimier"];
e[T].authorEmail = ["talou@timot.net"];
e[T].shortdesc = "Test current stylesheet in live browser";
e[T].description = "<p>EditCSS is a useful extension for web developers and web designers, that works for MozillaFirebird. It allows you to edit current stylesheets of a page in live, and display the result as you type. It appears in a sidebar. The project is based on Jesse Ruderman's \"Edit Style\" bookmarklet, that has done the essential work.</p>";
e[T].homepage = "http://editcss.mozdev.org/";
e[T].version = "0.01.1";
e[T].updated = "";
e[T].size = "36";
e[T].installFile = "http://downloads.mozdev.org/editcss/editcss.xpi";
T++;

e[T] = new extension("External Application Buttons");
e[T].id = "externalapp";
e[T].author = ["Torisugari"];
e[T].authorEmail = ["torisugari_moz@yahoo.co.jp"];
e[T].shortdesc = "Add buttons to the toolbar";
e[T].description = "<p>Launch other applications from your toolbar.</p>";
e[T].homepage = "http://cgi29.plala.or.jp/~mozzarel/";
e[T].version = "0.4";
e[T].updated = "";
e[T].size = "14";
e[T].installFile = "http://cgi29.plala.or.jp/~mozzarel/addon/firebird/externalapp/externalapp.xpi";
T++;

e[T] = new extension("Find in this Selectbox");
e[T].id = "findinselectbox";
e[T].author = ["Michael O'Rourke"];
e[T].authorEmail = ["momokatte@hotmail.com"];
e[T].shortdesc = "Adds a context menu item to selection boxes";
e[T].description = "<p>This adds a \"Find in this Selectbox\" dialog to Firebird so you can search listboxes on webpages just as easily as you can search the rest of the page.</p>";
e[T].homepage = "http://www.cosmicat.com/software/findinselect/";
e[T].version = "1.0";
e[T].updated = "";
e[T].size = "10.8";
e[T].installFile = "http://www.cosmicat.com/software/findinselect/findinselect.xpi";
T++;

e[T] = new extension("Firebird Help");
e[T].id = "fbh";
e[T].author = ["FBH Devs"];
e[T].authorEmail = ["brantgurganus2001@cherokeescouting.org"];
e[T].shortdesc = "Help documentation for Firebird.";
e[T].description = "<p>A port of the Seamonkey Help dialog to Mozilla Firebird with a coupleof cool extras to go with it :).</p>";
e[T].homepage = "http://firebirdhelp.mozdev.org/";
e[T].version = "0.4beta";
e[T].updated = "";
e[T].size = "10.8";
e[T].installFile = "http://downloads.mozdev.org/firebirdhelp/fbh0.4.xpi";
T++;

e[T] = new extension("Flash Click To View");
e[T].id = "flashclick";
e[T].author = ["Ted Mielczarek"];
e[T].authorEmail = ["luser_mozilla@perilith.com"];
e[T].shortdesc = "Replaces Flash objects with a button you must click to play the animation.";
e[T].description = "<p>Adds an XBL binding to Shockwave Flash object tags that replaces them with a button you must click in order to play the animation. Quite nice for restoring sanity to your browsing session.</p>";
e[T].homepage = "http://ted.mielczarek.org/code/mozilla/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://ted.mielczarek.org/code/mozilla/flashblock.xpi";
T++;

e[T] = new extension("GoHome");
e[T].id = "gohome";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Adds 'Home' to the context menu";
e[T].description = "<p>Adds 'Home' to the main context menu, immediately below 'Stop'.</p>";
e[T].homepage = "";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "2";
e[T].installFile = "http://downloads.mozdev.org/cdn/gohome/gohome.xpi";
T++;

e[T] = new extension("Google Bar");
e[T].id = "googlebar";
e[T].author = ["GoogleBar Team"];
e[T].authorEmail = [""];
e[T].shortdesc = "Brings the Google ToolBar to Mozilla";
e[T].description = "<p>Brings the http://toolbar.google.comGoogle ToolBar for IE to Mozilla.</p>";
e[T].homepage = "http://googlebar.mozdev.org/";
e[T].version = "0.6.0.17";
e[T].updated = "";
e[T].size = "109";
e[T].installFile = "http://googlebar.mozdev.org/XPI-stable.xpi";
T++;

e[T] = new extension("GoTo");
e[T].id = "goto";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Adds a Go To submenu to the context menu for links";
e[T].description = "<p>GoTo brings the functions of Digger to links!  Specifically, it adds a new Go To submenu to the context menu for links which lets you:</p><ul><li>Go to parent directories of the link, e.g. get to http://example.com/1/2/  from a link to http://example.com/1/2/somefolder/</li><li>Go to the ftp equivalent of an http link or vice versa</li><li>Climb up through the domain of the link, e.g. get to http://example.com/  from a link to http://subdomain.example.com/</li></ul>";
e[T].homepage = "";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://downloads.mozdev.org/cdn/goto/goto.xpi";
T++;

e[T] = new extension("GoUp");
e[T].id = "goup";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Easily navigate 'up' a level in a website";
e[T].description = "<p>Allows you to quickly move up a level in a site by pressing Alt + Up. Thisremoves the last segment from the url of the current page, and loads the newurl, i.e. http://example.com/folder/ goes to http://example.com/. Also,http://subdomain.example.com/ goes to http://example.com/.</p>";
e[T].homepage = "";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://downloads.mozdev.org/cdn/goup/goup.xpi";
T++;

e[T] = new extension("Gnusto");
e[T].id = "gnusto";
e[T].author = ["marnanel"];
e[T].authorEmail = [""];
e[T].shortdesc = "Play adventure games available in the Z-machine format.";
e[T].description = "<p>Play adventure games available in the Z-machine format.</p>";
e[T].homepage = "http://gnusto.mozdev.org/";
e[T].version = "0.5.0";
e[T].updated = "";
e[T].size = "110";
e[T].installFile = "http://downloads.mozdev.org/gnusto/gnusto-0.5.0.xpi";
T++;

e[T] = new extension("Grippies");
e[T].id = "grippies";
e[T].author = ["Neil Rashbrook"];
e[T].authorEmail = ["neil@parkwaycc.co.uk"];
e[T].shortdesc = "Adds Mozilla's splitter grippies to Firebird/Thunderbird";
e[T].description = "<p>Brings one of the Mozilla Application Suite's most loved/hatedfeatures to Firebird and Thunderbird: Splitter Grippies!</p><p>In Firebird the grippies are used to collapse the current sidebar.In Thunderbird they collapse the various panes in the main window.</p>";
e[T].homepage = "";
e[T].version = "0.1";
e[T].updated = "20031026";
e[T].size = "3";
e[T].installFile = "http://downloads.mozdev.org/database/extensions/grippies.xpi";
T++;

e[T] = new extension("Hide Searchbar");
e[T].id = "hidesearchbar";
e[T].author = ["Jordan Callicoat"];
e[T].authorEmail = [""];
e[T].shortdesc = "Hide or show the searchbar with Ctrl + Shift + S hotkey.";
e[T].description = "<p>Hide or show the searchbar with Ctrl + Shift + S hotkey.</p>";
e[T].homepage = "http://gratisdei.com/FB.htm";
e[T].version = "";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://gratisdei.com/hidesearch.xpi";
T++;

e[T] = new extension("IE View for Windows");
e[T].id = "ieview";
e[T].author = ["Paul Roub"];
e[T].authorEmail = ["paul@roub.net"];
e[T].shortdesc = "Open pages with IE";
e[T].description = "<p>Adds \"View page in Internet Explorer\" links to the content and linkcontext menu.  Handy for previewing pages in IE, loading up IE-onlypages when you run across them in Mozilla, etc.</p>";
e[T].homepage = "http://roub.net/xul/ieview/";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "11";
e[T].installFile = "http://roub.net/xul/ieview/ieview.xpi";
T++;

e[T] = new extension("ImageZoomer");
e[T].id = "imagezoomer";
e[T].author = ["Diesel"];
e[T].authorEmail = ["diesel69power@hotmail.com"];
e[T].shortdesc = "Allows zooming in/out of images from the context menu.";
e[T].description = "<p>Allows zooming in/out of images from the context menu.<ul><li>*adds two items to the context menu for images: Zoom In, Zoom Out</li><li>* Zoom In doubles the image's dimensions</li><li>* Zoom Out halves the image's dimensions</li></ul></p>";
e[T].homepage = "http://imagezoomer.mozdev.org/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://downloads.mozdev.org/imagezoomer/imageZoomer-v0.1.xpi";
T++;

e[T] = new extension("imgtag");
e[T].id = "imgtag";
e[T].author = ["Jedrek Kostecki"];
e[T].authorEmail = ["spam@kostecki.net"];
e[T].shortdesc = "Generates IMG tags and copies them to the clipboard with just a click.";
e[T].description = "<p>This extension gives you the ability to automatically generate xhtmlimg tags from any image you can view in Firebird, and copies it to theclipboard. </p>";
e[T].homepage = "http://kostecki.net/fb/";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://kostecki.net/fb/inst/imgtag.xpi";
T++;

e[T] = new extension("Java for Windows");
e[T].id = "java";
e[T].author = ["Kevin Burton"];
e[T].authorEmail = ["burton@newsmonster.org"];
e[T].shortdesc = "Easy installation of Java within Mozilla/Firebird.";
e[T].description = "<p>Easy installation of Java within Mozilla/Firebird.</p><p>Visit the project homepage for versions for other <abbr title=\"Operating Systems\">OSs</abbr>.</p>";
e[T].homepage = "http://java.mozdev.org/";
e[T].version = "1.4.1";
e[T].updated = "";
e[T].size = "9400";
e[T].installFile = "http://downloads.mozdev.org/java/jre-1_4_1_01-windows-i586-i.xpi";
T++;

e[T] = new extension("Javascript Console Status");
e[T].id = "jsstatus";
e[T].author = ["Michael O'Rourke"];
e[T].authorEmail = ["momokatte@hotmail.com"];
e[T].shortdesc = "Status bar icon for javascript warnings/errors.";
e[T].description = "<p>This extension displays an icon in the status bar whenever aJavaScript warning or error occurs in a webpage. Clicking on the iconopens the JavaScript Console.</p>";
e[T].homepage = "http://www.cosmicat.com/software/scriptstatus/";
e[T].version = "1.0";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://www.cosmicat.com/software/scriptstatus/scriptstatus.xpi";
T++;

e[T] = new extension("JS Console");
e[T].id = "jsconsole";
e[T].author = ["Daniel Fournier"];
e[T].authorEmail = ["dfour@noos.fr"];
e[T].shortdesc = "Tool for JavaScript developers to write and evaluate code snippets or JS files.";
e[T].description = "<p>JS Console is tool for JavaScript developers to write and evaluate code snippets or JS files. It provides an interface to use XPCOM components, libraries for I/O and RDF management, dynamic script loading, as well as an assertion unit framework for test-driven development.</p>";
e[T].homepage = "http://jsconsole.mozdev.org";
e[T].version = "1.1";
e[T].updated = "";
e[T].size = "250";
e[T].installFile = "http://jsconsole.mozdev.org/installation.html";
T++;

e[T] = new extension("Language Menu");
e[T].id = "langmenu";
e[T].author = ["Andrew Young"];
e[T].authorEmail = [""];
e[T].shortdesc = "Control what language you view web pages in";
e[T].description = "<p>This extension adds a submenu under 'Tools' which allows the user to selectthe 'Accept-Language' header that is sent to the server. This allows the serverto provide a localized version of a page.</p><p>Currently it supports 437 languages, thanks to the <a href=\"http://www.vaelen.org/cgi-bin/vaelen/vaelen.cgi?topic=languagemenu-languagepacks\">downloadable language packs</a></p>";
e[T].homepage = "http://www.vaelen.org/cgi-bin/vaelen/vaelen.cgi?topic=languagemenu-info";
e[T].version = "0.7";
e[T].updated = "";
e[T].size = "7";
e[T].installFile = "http://www.vaelen.org/languagemenu/languagemenu.xpi";
T++;

e[T] = new extension("Link Toolbar");
e[T].id = "linktoolbar";
e[T].author = ["Stephen Clavering", "Chris Neale"];
e[T].authorEmail = ["mozilla@clav.me.uk", "cdn@mozdev.org"];
e[T].shortdesc = "Brings Mozilla's 'Site Navigation Bar' to Firebird";
e[T].description = "<p>Adds a panel to the status bar with buttons and menus to goto the top of the current site, up a level in the site, to thefirst/previous/next/last page in the current sequence, or otherpage related to the current one.  Web pages provide the URLs forthe buttons using the HTML <code>&lt;link&gt;</code> element,or they can be generated by the LinkIt extension.</p><p>While originally based on Mozilla's &lsquo;Site NavigationToolbar&rsquo;, significant development has occurred since thecreation of the extension:  all the buttons and menuitems canbe middle clicked to open the link in a new tab (or window);multiple Top/Up/First/Prev/Next/Last links are supported; andan optional \"icons only\" mode is included to reduce the spaceused.  (Other less obvious enhancements are also present.)</p>";
e[T].homepage = "http://cdn.mozdev.org/linkToolbar/";
e[T].version = "0.6.1";
e[T].updated = "20031009";
e[T].size = "20";
e[T].installFile = "http://downloads.mozdev.org/cdn/linkToolbar/linkToolbar.xpi";
T++;

e[T] = new extension("LinkIt");
e[T].id = "linkit";
e[T].author = ["Stephen Clavering", "Chris Neale"];
e[T].authorEmail = ["mozilla@clav.me.uk", "cdn@mozdev.org"];
e[T].shortdesc = "Improves website navigation";
e[T].description = "<p>LinkIt enhances the Link Toolbar (either the extension for Firebird orthe Site Navigation Toolbar included in Mozilla) by scanning all the linksin a page for ones which seem to be describing some kind of previous or nextpage relationship, and mapping these to the appropriate buttons on the toolbar.It also generates Up and Top links, based on the URL of the page. Both thesefunctions are helpful, because very few sites actually include the appropriateHTML to support the Link Toolbar directly at the moment.</p><p>Be aware that as these links are generated based on automated guesswork, therewill be occasional mistakes.</p>";
e[T].homepage = "http://cdn.mozdev.org/linkToolbar/";
e[T].version = "0.0.5";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://downloads.mozdev.org/cdn/linkit/linkit.xpi";
T++;

e[T] = new extension("Linky");
e[T].id = "linky";
e[T].author = ["Henrik Gemal"];
e[T].authorEmail = [""];
e[T].shortdesc = "Adds more link options to the context menu";
e[T].description = "<p>Linky is a very simple addon to the context menuthat provide you with the following:</p><ul><li>Opens all links in a selection in new tabs or windows</li><li>Finds and opens link in plain text in a new tab or window</li><li>Opens all links on page in new tabs or windows, etc.</li></ul><p>The Mozilla version also works in Mail.</p>";
e[T].homepage = "http://gemal.dk/mozilla/linky.html";
e[T].version = "2.0.0";
e[T].updated = "";
e[T].size = "29";
e[T].installFile = "http://downloads.mozdev.org/linky/linky-200.xpi";
T++;

e[T] = new extension("Link Visitor");
e[T].id = "linkvisitor";
e[T].author = ["Billy"];
e[T].authorEmail = ["bllaw@mmu.edu.my"];
e[T].shortdesc = "Mark links as visited or unvistited from the context menu";
e[T].description = "<p>Adds options to the context menu to let you:</p><ul>  <li>mark a link as visited or unvisited</li>  <li>mark all selected links as visited</li>  <li>mark all selected links as unvisited</li></ul>";
e[T].homepage = "http://linkvisitor.mozdev.org/";
e[T].version = "0.30";
e[T].updated = "";
e[T].size = "9";
e[T].installFile = "http://downloads.mozdev.org/linkvisitor/linkvisitor-030.xpi";
T++;

e[T] = new extension("Live HTTP Headers");
e[T].id = "livehttpheaders";
e[T].author = ["Daniel Savard"];
e[T].authorEmail = ["savardd@gnulinux.ca"];
e[T].shortdesc = "Developer tool to show information about HTTP headers";
e[T].description = "<p>Adds information about the HTTP headers in 3 ways:</p><ul><li>By adding a 'Headers' tab in 'View Page Info' of a web page.</li><li>By adding a tool in the 'Tools->Web Development' menu to be able  to display http headers in real time</li><li>By letting you edit request headers and replay a URL.</li></ul>";
e[T].homepage = "http://livehttpheaders.mozdev.org/";
e[T].version = "0.7";
e[T].updated = "";
e[T].size = "28";
e[T].installFile = "http://downloads.mozdev.org/livehttpheaders/livehttpheaders.xpi";
T++;

e[T] = new extension("Macro Editor");
e[T].id = "macroeditor";
e[T].author = ["Biju G. C"];
e[T].authorEmail = [""];
e[T].shortdesc = "Easily create/run macros written in Javascript";
e[T].description = "<p>Macro Editor was created with the aim of providing a simple toolto write and test macros for Mozilla, Firebird, Thunderbird, therebyincreasing participation of more developers and thus accelerating development of more extension and programs for Mozilla and relatedproducts.</p><p>Features:</p><p>Adds a Macro menu (under the Tools menu) which contains menu itemsfor macro editor, evaluate a javascript expression, execute a javascriptstatement, and an option to open a XUL file in new window (very usefulin Thunderbird). Once you create macros they will also appear as a menuitem.</p>";
e[T].homepage = "http://macroeditor.mozdev.org/";
e[T].version = "2003.0721.0";
e[T].updated = "";
e[T].size = "9";
e[T].installFile = "http://downloads.mozdev.org/quicktools/MacroEditor.xpi";
T++;

e[T] = new extension("Magpie");
e[T].id = "magpie";
e[T].author = ["Ben Goodger"];
e[T].authorEmail = ["mozilla@bengoodger.com"];
e[T].shortdesc = "Provides a number of tools to make media collection more efficient";
e[T].description = "<p>Magpie 3.0 (formerly known as Tab Downloader) provides a number of tools to make media collection more efficient. It can save files (images, movies, whatever) that are open in background tabs automatically to a time stamped folder, as well as saving all links on a page of a particular type. This makes it very easy to bulk download images from websites. Also included is a URL Interceptor to strip valid URLs out of CGI redirects, and a numeric digit flipper for the page location.</p><p>Incompatibility:</p><p>This extension's shortcut for digit flipper decrement conflicts with the TBE extension shortcut for undo close tab (Ctrl+Shift+Z).</p>";
e[T].homepage = "http://www.bengoodger.com/software/tabloader/";
e[T].version = "3.0";
e[T].updated = "";
e[T].size = "15";
e[T].installFile = "http://extensionroom.mozdev.org/install.php/http://www.bengoodger.com/software/tabloader/magpie3_0.xpi";
T++;

e[T] = new extension("Minesweeper");
e[T].id = "minesweeper";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Classic and Hexagonal Minesweeper";
e[T].description = "<p>The classic game of Minesweeper written in XUL+Javascript. Theappearance is very similar to the Windows XP version of the game,though it also features a hexagonal mode.</p><p>Once installed the game can be accessed by choosing \"PlayMinesweeper\" from the Tools menu in Firebird.</p>";
e[T].homepage = "";
e[T].version = "0.5";
e[T].updated = "";
e[T].size = "11";
e[T].installFile = "http://downloads.mozdev.org/cdn/minesweeper/minesweeper.xpi";
T++;

e[T] = new extension("MNG Support for Windows");
e[T].id = "mngsupport";
e[T].author = ["Christian Biesinger"];
e[T].authorEmail = ["cbiesinger@web.de"];
e[T].shortdesc = "Support for MNG (Animated PNGs). ";
e[T].description = "<p>MNG (Animated PNGs) Support was removed as part of Mozilla/Firebird on 2003-06-03.This extension allows you to view sites/themes/ and images that utilize MNG</p>";
e[T].homepage = "http://stud4.tuwien.ac.at/~e0225227/";
e[T].version = "";
e[T].updated = "";
e[T].size = "100";
e[T].installFile = "http://downloads.mozdev.org/quicktools/mng-windows-fb.xpi";
T++;

e[T] = new extension("Mouse Gestures");
e[T].id = "mousegest";
e[T].author = ["Optimoz Team"];
e[T].authorEmail = [""];
e[T].shortdesc = "Elegantly control your browser by drawing gestures.";
e[T].description = "<p>The Mouse Gestures extension lets you invoke commands just by drawinggestures with your mouse, over the webpage you are viewing. Forexample, you can go back one page just by holding down the mousebutton, moving to the left and then releasing the button. Usinggestures is much more convenient than using toolbars or menus.This extension provides you with gestures for navigation, bookmarking,tab switching, font and image zooming... and it even supportsMozilla's Mail & News client. It also includes \"Rocker Gestures\" thatare even faster than normal gestures and you can now edit all gesturemappings using a simple interface - including those for rockergestures and mouse wheel rockers.</p>";
e[T].homepage = "http://optimoz.mozdev.org/gestures/";
e[T].version = "0.4pre";
e[T].updated = "";
e[T].size = "30";
e[T].installFile = "http://downloads.mozdev.org/optimoz/nightly/mozgest_20031019.xpi";
T++;

e[T] = new extension("Mozilla Amazon Browser (MAB)");
e[T].id = "mozamazon";
e[T].author = ["Fabio Serra"];
e[T].authorEmail = [""];
e[T].shortdesc = "A XUL interface for the amazon.com and .co.uk product catalogues";
e[T].description = "<p>Allows you to perform searches against the Amazon.com orAmazon.co.uk product catalogue and see the results from aninterface desktop-like. If you want to buy a product or goingdirectly to Amazon.com, you have to select a product from theresult list and click on &ldquo;Go Amazon&rdquo; button orusing the keyboard shortcuts ALT+G.</p><p>The User Interface is completely customizable.</p><p>You can try it out before installing by clicking <ahref=\"http://www.infodraft.com/~faser/mab/content/mab.xul\">here</a>.</p>";
e[T].homepage = "http://mab.mozdev.org/";
e[T].version = "1.0.0.1";
e[T].updated = "20030809";
e[T].size = "44";
e[T].installFile = "http://downloads.mozdev.org/mab/mab.xpi";
T++;

e[T] = new extension("mozCalc");
e[T].id = "mozcalc";
e[T].author = ["Biju G. C"];
e[T].authorEmail = [""];
e[T].shortdesc = "An easy to use XUL calculator";
e[T].description = "<p>This is a Firebird/ThunderBird port of Martin T. Kutschker's mozCalc (http://mozcalc.mozdev.org/).An easy to use XUL calculator. Modes avilable are Normal, Scientific, Reverse Polish Notation and sidebar.Take a look at the screenshots <a href=\"http://downloads.mozdev.org/quicktools/img/mozcalc/mozcalc5.png\">Simple view</a> and <a href=\"http://downloads.mozdev.org/quicktools/img/mozcalc/mozcalc1.png\">Full feature view</a>.</p>";
e[T].homepage = "http://quicktools.mozdev.org/mozcalc";
e[T].version = "2003.1013.0";
e[T].updated = "";
e[T].size = "37";
e[T].installFile = "http://downloads.mozdev.org/quicktools/mozcalc.xpi";
T++;

e[T] = new extension("MozEdit");
e[T].id = "mozedit";
e[T].author = ["Mark Bokil"];
e[T].authorEmail = ["mbokil@bokil.com"];
e[T].shortdesc = "Adds an advanced text editor to Firebird.";
e[T].description = "<p>Adds an advanced text editor to Firebird. The editor offers quick editing of chrome and user.js files, html preview, document history, autobackup, find/replace with regex, JavaScript Console, multiple document buffers, a command line to run programs, and an edit in Mozedit new Tools menu option.</p>";
e[T].homepage = "http://mozedit.mozdev.org/";
e[T].version = "0.1.1pre";
e[T].updated = "";
e[T].size = "108";
e[T].installFile = "http://downloads.mozdev.org/mozedit/mozedit-9-20-03.xpi";
T++;

e[T] = new extension("MozEX");
e[T].id = "mozex";
e[T].author = ["Tomas Styblo"];
e[T].authorEmail = [""];
e[T].shortdesc = "Adds support to allows the user to use external programs";
e[T].description = "<p>Allows the user to use external programs for: view page source, edit content of textareas handle mailto, news, telnet and FTP links and download files </p>";
e[T].homepage = "http://mozex.mozdev.org/";
e[T].version = "1.07";
e[T].updated = "";
e[T].size = "15";
e[T].installFile = "http://mozex.mozdev.org/mozex-1.07.xpi";
T++;

e[T] = new extension("MozFBRH");
e[T].id = "mozfbrh";
e[T].author = ["Paradox"];
e[T].authorEmail = ["Paradox5555@hotmail.com"];
e[T].shortdesc = "Adds middle-click behavior to Forward, Back, Reload, and Home to launch new tab.";
e[T].description = "<p>MozFBRH (Mozilla Forward/Backward/Reload/Home) is avery simple extension that allows you to middle click on the Forward,Back, Reload, Home, and throbber buttons to open them in a new tab.When this is done to Back, Forward, or Reload the entire sessionhistory is copied to the new tab (similar to TBE's duplicate tab),allowing you to use the forward/back buttons in the new tab as well.</p><p>Current Limitations:</p><ol><li>Middle clicking \"Reload\" always does a network (non-cache) reloadin a new tab. If people want it I'll try to add shift+middleclicksupport so that you can choose cache reload or network reload.</li><li>This extension does nothing with the Forward/Back context menus,only the buttons themself. Since TBE provides middle click support forthe Back/Forward context menus I wasn't sure if I could add thismyself without causing conflicts.</li><li>\"Go\" button is not touched, because similarly I think this wouldconflict with Digger.</li><li>Doesn't do anything for the \"Stop\" button either....but honestly Icouldn't think of any practical use for \"stop this page loading in anew tab\".....in fact is that even possible??</li></ol>";
e[T].homepage = "http://mozfbrh.mozdev.org/";
e[T].version = "0.6.1";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://extensionroom.mozdev.org/install.php/http://home.comcast.net/~jkeis10/mozFBRH.xpi";
T++;

e[T] = new extension("Msnmsgr");
e[T].id = "msnmsgr";
e[T].author = ["Kevin Bowes"];
e[T].authorEmail = ["kevin@sykosoft.net"];
e[T].shortdesc = "A crossplatform alternative to MSN Messenger.";
e[T].description = "<p>A cross-platform alternative to MSN Messenger.  It adds a menu item to the tools menu andoptionally adds an button to the toolbar (available via the normal customisation palette).</p>";
e[T].homepage = "http://msnmsgr.mozdev.org/";
e[T].version = "0.5.0";
e[T].updated = "";
e[T].size = "45";
e[T].installFile = "http://downloads.mozdev.org/msnmsgr/msnmsgr.xpi";
T++;

e[T] = new extension("NavButtons");
e[T].id = "navbuttons";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Useful site navigation toolbar buttons";
e[T].description = "<p>NavButtons is a variant of the Link Toolbar which adds buttons for Top andUp, and First, Previous, Next and Last page to the set of available buttons inthe toolbar customisation panel.  The webpage to which these buttons takes youis specified by the page author using the HTML <code>LINK</code> element.</p><p>Installing LinkIt as well as this extension is recommened, because few webpage authors bother to provide the links that this extension uses. LinkIt willgenerate them using guesswork.</p>";
e[T].homepage = "";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "15";
e[T].installFile = "http://downloads.mozdev.org/cdn/navbuttons/navbuttons.xpi";
T++;

e[T] = new extension("NeedleSearch");
e[T].id = "needlesearch";
e[T].author = ["Eelco van Kuik"];
e[T].authorEmail = [""];
e[T].shortdesc = "A very powerful search toolbar";
e[T].description = "<p>The NeedleSearch toolbar lets you bookmark search engines.NeedleSearch can handle ALL search engines, the information can beposted too! There is no need to first go to the website for a new searchengine, the included auto-add function enables anybody to add his or herown search engines on the spot.</p>";
e[T].homepage = "http://needlesearch.mozdev.org/";
e[T].version = "2.2.3";
e[T].updated = "";
e[T].size = "100";
e[T].installFile = "http://downloads.mozdev.org/needlesearch/NeedleSearch-current.xpi";
T++;

e[T] = new extension("NewsMonster");
e[T].id = "newsmonster";
e[T].author = ["Kevin Burton"];
e[T].authorEmail = ["burton@newsmonster.org"];
e[T].shortdesc = "RSS aggregator and weblog manager.";
e[T].description = "<p>NewsMonster is a news, weblog, and RSS aggregator that runs in directly in yourweb browser. NewsMonster offers a superior web experience and outstandingintegration with existing websites and weblogs that support RSS. Even sitesthat don't support RSS can work with NewsMonster. That's not all! NewsMonsterincorporates an advanced reputation system to prevent spam and discover andinform you of important news.</p><p>It's recommended that you visitthis extension's homepage before installing it anyway.</p>";
e[T].homepage = "http://newsmonster.org/";
e[T].version = "1.2.2";
e[T].updated = "";
e[T].size = "220";
e[T].installFile = "http://www.newsmonster.org/download/newsmonster-1.2.2-final-1065627885-pro.xpi";
T++;

e[T] = new extension("Next/Prev Image");
e[T].id = "nextimage";
e[T].author = ["Ralph Churchill"];
e[T].authorEmail = ["churchillrm@cox.net"];
e[T].shortdesc = "Automatically increment image URLs (for image galleries)";
e[T].description = "<p>A handy little extension for automagically incrementing (numerical)image URLs, allowing you to make your own \"ad hoc\" image gallery.</p>";
e[T].homepage = "http://members.cox.net/churchillrm/install.html";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://extensionroom.mozdev.org/install.php/http://members.cox.net/churchillrm/nextimage.xpi";
T++;

e[T] = new extension("Nuke Anything");
e[T].id = "nukeanything";
e[T].author = ["Ted Mielczarek"];
e[T].authorEmail = ["luser_mozilla@perilith.com"];
e[T].shortdesc = "Remove an object from the page via the context menu";
e[T].description = "<p>Remove an object from the page via the context menu</p>";
e[T].homepage = "http://ted.mielczarek.org/code/mozilla/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://ted.mielczarek.org/code/mozilla/nukeanything.xpi";
T++;

e[T] = new extension("Nuke Image");
e[T].id = "nukeimage";
e[T].author = ["Ted Mielczarek"];
e[T].authorEmail = ["luser_mozilla@perilith.com"];
e[T].shortdesc = "Remove an image from the page via the context menu";
e[T].description = "<p>Allows one to remove an image from layout via the context menu.</p>";
e[T].homepage = "http://ted.mielczarek.org/code/mozilla/";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://ted.mielczarek.org/code/mozilla/nukeimage.xpi";
T++;

e[T] = new extension("Offline");
e[T].id = "offlinefb";
e[T].author = ["Motohiko"];
e[T].authorEmail = ["amotohiko_mozillafirebird@yahoo.co.jp"];
e[T].shortdesc = "Ability to set FB offline";
e[T].description = "<p>Ability to set FB offline</p>";
e[T].homepage = "http://www.geocities.co.jp/SiliconValley-SanJose/9076/offline/index.en.html";
e[T].version = "2";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://www1.ttcn.ne.jp/~amotohiko/offline.0831.xpi";
T++;

e[T] = new extension("Ook");
e[T].id = "ook";
e[T].author = ["Chris Neale", "Stephen Clavering"];
e[T].authorEmail = ["cdn@mozdev.org", "mozilla@clav.me.uk"];
e[T].shortdesc = "Access your bookmarks from the context menu";
e[T].description = "<p>Ook is an extremely simple extension that duplicates the bookmarksmenu at the bottom of the context menu.  This is very handy for thosewho hide the menus and/or the bookmarks toolbar.</p>";
e[T].homepage = "http://cdn.mozdev.org/";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "2";
e[T].installFile = "http://downloads.mozdev.org/cdn/ook/ook.xpi";
T++;

e[T] = new extension("Optimoz Tweaks");
e[T].id = "optimoztweaks";
e[T].author = ["Optimoz Team"];
e[T].authorEmail = [""];
e[T].shortdesc = "Automatically hides/shows the sidebar";
e[T].description = "<p>Automatically hides the sidebar when the mouse cursor is over the webpage. Configurable delay and sensitivity.</p>";
e[T].homepage = "http://optimoz.mozdev.org/tweaks/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "25";
e[T].installFile = "http://downloads.mozdev.org/optimoz/moztweaks_0_1.xpi";
T++;

e[T] = new extension("Paste and Go");
e[T].id = "pasteandgo";
e[T].author = ["Jens Bannmann"];
e[T].authorEmail = ["jens.b@web.de"];
e[T].shortdesc = "Paste a URI from the clipboard and automatically go there";
e[T].description = "<p>This extension lets you paste an URL from the clipboard into the address bar andload it as a single step, either via the address bar's context menu or by pressingCtrl-Shift-V. Additionally, it provides a Paste and Search command for MozillaFirebird's search bar (via context menu or Ctrl-Shift-X).</p>";
e[T].homepage = "http://tecwizards.de/mozilla/";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://tecwizards.de/mozilla/pasteandgo_0_2.xpi";
T++;

e[T] = new extension("Paste IP");
e[T].id = "pasteip";
e[T].author = ["Michael Newton"];
e[T].authorEmail = ["pasteip-owner@mozdev.org"];
e[T].shortdesc = "Adds items to the context menu of textboxes, allowing you to paste your IP address or User Agent string";
e[T].description = "<p>Adds items to the context menu of textboxes, allowing you to paste your IP address or User Agent string.</p>";
e[T].homepage = "http://pasteip.mozdev.org";
e[T].version = "1.0";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://downloads.mozdev.org/pasteip/pasteip.xpi";
T++;

e[T] = new extension("PNH Developers' Toolbar");
e[T].id = "pnhtoolbar";
e[T].author = ["Chris Casciano"];
e[T].authorEmail = ["chris@placenamehere.com"];
e[T].shortdesc = "Useful toolbar for web developers";
e[T].description = "<p>The PNH Developer Toolbar is an additional toolbar containing acollection of tools that web page builders may find helpful. Itfeatures outlining elements in a page, validating it throughdifferent engines, resizing the window, and other very useful toolsfor the developer.</p>";
e[T].homepage = "http://placenamehere.com/pnhtoolbar/";
e[T].version = "0.51";
e[T].updated = "";
e[T].size = "8";
e[T].installFile = "http://placenamehere.com/pnhtoolbar/pnhfbtoolbar.xpi";
T++;

e[T] = new extension("Popup ALT Attributes");
e[T].id = "popupalt";
e[T].author = ["Shimoda Hiroshi"];
e[T].authorEmail = ["piro@p.club.ne.jp"];
e[T].shortdesc = "Add-on to popup alternate text given for images as ALT attributes";
e[T].description = "<p>This is an add-on package to popup alternate texts given as ALTattributes (they are not descriptions, but authors often use theattribute only for popups), like NC4, IE, and other browsers.</p>";
e[T].homepage = "http://white.sakura.ne.jp/~piro/xul/_popupalt.html.en";
e[T].version = "1.2.2003031502";
e[T].updated = "";
e[T].size = "13";
e[T].installFile = "http://white.sakura.ne.jp/~piro/xul/xpi/popupalt_en.xpi";
T++;

e[T] = new extension("Popup Count");
e[T].id = "popupcount";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Counts the number of blocked popups on each webpage.";
e[T].description = "<p>Counts the number of blocked popups on each webpage, displaying the number in the statusbar. Additionally the all-time total number of blocked popups is displayed in either a tooltip or the statusbar.</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/extensions/";
e[T].version = "0.2.5";
e[T].updated = "";
e[T].size = "13";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/popupcount.xpi";
T++;

e[T] = new extension("PrefButtons");
e[T].id = "prefbuttons";
e[T].author = ["Stephen Clavering"];
e[T].authorEmail = ["mozilla@clav.me.uk"];
e[T].shortdesc = "Access frequently used prefs from the toolbar";
e[T].description = "<p>PrefButtons takes the most frequently used items from the Preferences Toolbar(fonts, colours, java, javascript etc.), and adds them to the normal toolbarcustomisation dialogue, for you to place where you want.</p><p>It also includes Image, Javascript and Plugins toggles that apply to the currenttab only, which are not yet included in the Preferences Toolbar.</p>";
e[T].homepage = "";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://downloads.mozdev.org/cdn/prefbuttons/prefbuttons.xpi";
T++;

e[T] = new extension("Preferential");
e[T].id = "preferential";
e[T].author = ["Stephen Bounds"];
e[T].authorEmail = ["GuruJ@mbox.com.au"];
e[T].shortdesc = "Simple, accessible GUI that allows the modification of any preference set";
e[T].description = "<p>Aims to provide all users of Gecko browsers (eg. Mozilla, Firebird)with a simple, accessible GUI that allows the modification of anypreference set within that browser environment.</p>";
e[T].homepage = "http://preferential.mozdev.org/";
e[T].version = "0.5.3";
e[T].updated = "";
e[T].size = "68";
e[T].installFile = "http://downloads.mozdev.org/preferential/preferential.xpi";
T++;

e[T] = new extension("QuickManager");
e[T].id = "quickmanager";
e[T].author = ["Biju G. C"];
e[T].authorEmail = [""];
e[T].shortdesc = "Extensions and Themes manager for Thunderbird.";
e[T].description = "<p> QuickManager project aims to develop a tool to easily install andmanage Extensions and Themes in Mozilla Products.</p> <p><ahref=\"http://quickmanager.mozdev.org/screenshots.html\">Screenshots</a> for this extension is available.</p>";
e[T].homepage = "http://quickmanager.mozdev.org/";
e[T].version = "2003.1021.0";
e[T].updated = "";
e[T].size = "21";
e[T].installFile = "http://downloads.mozdev.org/quickmanager/QuickManager.xpi";
T++;

e[T] = new extension("QuickNote");
e[T].id = "quicknote";
e[T].author = ["Jed Brown"];
e[T].authorEmail = ["jedbro@ifrance.com"];
e[T].shortdesc = "A 'Post-It' like notepad.";
e[T].description = "<p>QuickNote is a note taking-like extension slightly modeled after 'Post-It', 'Sticky', and the \"Quick Notepad\" plugin for <a href=\"http://www.jedit.org/\">jedit</a>.</p><p>Current features include; Autosave, up to 4 tabs for notes, user defined notes, open in SideBar, tab or window, <a href=\"http://quicknote.mozdev.org/icons.html\">Toolbar icon</a>, send selected text to, Save As and more.</p>";
e[T].homepage = "http://quicknote.mozdev.org/";
e[T].version = "0.4pre";
e[T].updated = "";
e[T].size = "64";
e[T].installFile = "http://downloads.mozdev.org/quicknote/quicknote.xpi";
T++;

e[T] = new extension("QuickPrefs");
e[T].id = "quickprefs";
e[T].author = ["HJ van Rantwijk", "Chris Neale"];
e[T].authorEmail = ["", "cdn@mozdev.org"];
e[T].shortdesc = "Provides a button that allows quick pref toggling.";
e[T].description = "<p>Re-Localised version of HJ's 20021015 QuickPrefs for Mozilla Firebird, recently tweaked to include more Qute-like icons</p>";
e[T].homepage = "http://quickprefs.mozdev.org/";
e[T].version = "Oct-15 [ Jun-17 1.0.1u ]";
e[T].updated = "";
e[T].size = "40";
e[T].installFile = "http://downloads.mozdev.org/cdn/hj-quickprefs/quickprefs-fb.xpi";
T++;

e[T] = new extension("Quick Tools");
e[T].id = "quicktools";
e[T].author = ["Biju G. C"];
e[T].authorEmail = [""];
e[T].shortdesc = "Adds a few extra tools/options to FB and TB";
e[T].description = "<p>The QuickTools versions for Firebird adds a \"Calendar\" item in \"Tools\" menu to allow you to run the \"Calendar\" extension from the menu</p><p>For ThunderBird it adds two items in Tools menu: Install Theme from URL and Install Extension from URL</p>";
e[T].homepage = "http://quicktools.mozdev.org/";
e[T].version = "2003.0805.0";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://downloads.mozdev.org/quicktools/QuickTools.xpi";
T++;

e[T] = new extension("RadialContext");
e[T].id = "radialcontext";
e[T].author = ["Jens"];
e[T].authorEmail = ["jens@gamemakers.de"];
e[T].shortdesc = "A hierarchical, context-sensitive pie menu";
e[T].description = "<p>A hierarchical, context-sensitive pie menu. It offers an alternativeto both the normal context menu and mouse gestures. The feeling is verysimilar to mouse gestures. But there also is a GUI so you don't have tolook up what options are available in the given context.</p>";
e[T].homepage = "http://www.gamemakers.de/mozilla/radialcontext/";
e[T].version = "1.0rc3";
e[T].updated = "20030726";
e[T].size = "100";
e[T].installFile = "http://www.radialthinking.de/radialcontext/RadialContext_fb.xpi";
T++;

e[T] = new extension("Moji");
e[T].id = "moji";
e[T].author = ["Erwan Loisant"];
e[T].authorEmail = ["erwan@loisant.org"];
e[T].shortdesc = "Helper for Japanese language learners.";
e[T].description = "<p>Moji provides a set of tools such as dictionary, kanji dictionary and inline tooltips to help foreigners learning Japanese level to read webpages in this language. Note that Moji requires jslib to work properly, see homepage for more information.</p>";
e[T].homepage = "http://moji.mozdev.org/";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "96";
e[T].installFile = "http://downloads.mozdev.org/moji/moji.xpi";
T++;

e[T] = new extension("RSS Reader Panel");
e[T].id = "rssreaderpanel";
e[T].author = ["flyson"];
e[T].authorEmail = ["flyson@toys.co.jp"];
e[T].shortdesc = "RSS Feed Reader Extension.";
e[T].description = "<p>RSS Feed Reader Panel.</p>";
e[T].homepage = "http://fls.moo.jp/moz/rssreader.html";
e[T].version = "1.11";
e[T].updated = "";
e[T].size = "16.0";
e[T].installFile = "http://fls.moo.jp/moz/rssreader/rssreader_111.xpi";
T++;

e[T] = new extension("Search Button");
e[T].id = "searchbutton";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Adds a Search button (for use with the Search Bar) to the customize toolbar window.";
e[T].description = "<p>Adds a Search button (for use with the Search Bar) to the customize toolbar window. By default left-click opens search results in the current tab and middle-click opens search results in a new tab. To display the Search button, right-click on the toolbar and select Customize..., then drag the button where you want it.</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/#sb";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "8";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/searchbutton.xpi";
T++;

e[T] = new extension("Search Button Lite");
e[T].id = "searchbuttonlite";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Allows the Search Bar's engine icon to be used to initiate a search.";
e[T].description = "<p>Allows the Search Bar's engine icon to be used to initiate a search. Each mouse button can be customised to open search results in the current tab, in a new tab or to open the search engine menu. The default behaviour of the Enter key may also be changed to open search results in a new tab. The extension can be customised by changing the options in the Extensions panel of the Options dialog box.</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/#sbl";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/searchbuttonlite.xpi";
T++;

e[T] = new extension("SearchThis!");
e[T].id = "searchthis";
e[T].author = ["Darryl Mlinar"];
e[T].authorEmail = ["dmlinar@yahoo.com"];
e[T].shortdesc = "Search for selected text on a variety of websites";
e[T].description = "<p>SearchThis! is a Firebird extension that will greatly enhance your web browsing experience.It adds three items to the right-click context menu which allow you to search for your selectedtext on major sites. Currently included websites are Dictionary.com, IMDb.com, and Amazon.com.</p>";
e[T].homepage = "http://searchthis.mozdev.org";
e[T].version = "1.0";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://searchthis.mozdev.org/st.xpi";
T++;

e[T] = new extension("Scribe");
e[T].id = "scribe";
e[T].author = ["Jeremiah Golden"];
e[T].authorEmail = ["scribe@prismicspiral.com"];
e[T].shortdesc = "Adds Word Processor like functionality to web forms, including opening and saving form entries as files.";
e[T].description = "<p>Adds Word Processor like functionality to web forms, includingopening and saving form entries as files.</p>";
e[T].homepage = "http://www.prismicspiral.com/scribe/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "28";
e[T].installFile = "http://www.prismicspiral.com/scribe/scribe.xpi";
T++;

e[T] = new extension("Session Saver");
e[T].id = "sessionsaver";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Remembers loaded tabs and their history items when Firebird is closed.";
e[T].description = "<p>Remembers loaded tabs and their history items when Firebird is manually closed, then restores the tabs and history items when next started. The saved session can also be manually restored or updated at any later time via the items in the File menu.</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/";
e[T].version = "0.1.1";
e[T].updated = "";
e[T].size = "13";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/sessionsaver.xpi";
T++;

e[T] = new extension("Slashzilla");
e[T].id = "slashzilla";
e[T].author = ["Andrew Kuttig"];
e[T].authorEmail = [""];
e[T].shortdesc = "An enhanceded interface to Slashdot through a sidebar.";
e[T].description = "<p>A sidebar panel that provides the user with an enhancement tothe interface provided by Slashdot.</p>";
e[T].homepage = "http://slashzilla.mozdev.org/";
e[T].version = "0.05";
e[T].updated = "";
e[T].size = "80";
e[T].installFile = "http://slashzilla.mozdev.org/slashzilla0_05.xpi";
T++;

e[T] = new extension("SmoothWheel");
e[T].id = "smoothwheel";
e[T].author = ["Avi Halachmi"];
e[T].authorEmail = ["avihpit@yahoo.com"];
e[T].shortdesc = "Scroll the page smoothly with the mouse wheel";
e[T].description = "<p>Allows you to scroll the page smoothly with the mouse wheelutilizing several smart algorithms for smoothness and adaptive behaviour and is completely configurable, including 10 presets. It can enhance/replace the internal Gecko smoothscroll which was introduced on 2003-03-24.</p>";
e[T].homepage = "http://smoothwheel.mozdev.org/";
e[T].version = "0.32";
e[T].updated = "";
e[T].size = "20";
e[T].installFile = "http://downloads.mozdev.org/smoothwheel/smoothwheel.xpi";
T++;

e[T] = new extension("Spiderzilla for Windows");
e[T].id = "spiderzilla";
e[T].author = ["lenrock"];
e[T].authorEmail = [""];
e[T].shortdesc = "A utility for downloading complete websites";
e[T].description = "<p>Spiderzilla is an easy to use website download utility.  It uses an externalOpen Source program Httrack Webside Copier (embedded in the Windows version).It allows you to download whole websites from the internet to a local directory,recreating the directory structure, and retrieving all html files, images, etc.</p><p>Once installed it can be found under Tools &gt; Download This Site.</p>";
e[T].homepage = "http://len-rock.w.interia.pl/mozia_en.htm";
e[T].version = "1.05";
e[T].updated = "";
e[T].size = "679";
e[T].installFile = "http://www.dlaciebie.net/programy/mozilla/spiderzilla/spiderzilla.xpi";
T++;

e[T] = new extension("Spiderzilla for Linux");
e[T].id = "spiderzilla";
e[T].author = ["lenrock"];
e[T].authorEmail = [""];
e[T].shortdesc = "A utility for downloading complete websites";
e[T].description = "<p>Spiderzilla is an easy to use website download utility.  It uses an externalOpen Source program Httrack Webside Copier (embedded in the Windows version).It allows you to download whole websites from the internet to a local directory,recreating the directory structure, and retrieving all html files, images, etc.</p><p>Once installed it can be found under Tools &gt; Download This Site.</p>";
e[T].homepage = "http://len-rock.w.interia.pl/mozia_en.htm";
e[T].version = "1.05";
e[T].updated = "";
e[T].size = "27";
e[T].installFile = "http://www.dlaciebie.net/programy/mozilla/spiderzilla/spiderzilla_lin.xpi";
T++;

e[T] = new extension("Statusbar Clock");
e[T].id = "statusbarclock";
e[T].author = ["Michael O'Rourke"];
e[T].authorEmail = ["momokatte@hotmail.com"];
e[T].shortdesc = "Date and time on the status bar";
e[T].description = "<p>Date and time on the status bar</p>";
e[T].homepage = "http://www.cosmicat.com/software/timestatus/";
e[T].version = "1.3.1";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://www.cosmicat.com/software/timestatus/timestatus.xpi";
T++;

e[T] = new extension("Statusbar On Top");
e[T].id = "statusbarontop";
e[T].author = ["Willll and Jensb"];
e[T].authorEmail = ["doingitinstyle@hotmail.com"];
e[T].shortdesc = "This extension moves the status bar to the top of the screen, between bookmarks and tabs.";
e[T].description = "<p>This extension moves the status bar to the top of the screen, between bookmarks and tabs.</p>";
e[T].homepage = "http://statustop.mozdev.org/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "2";
e[T].installFile = "http://statustop.mozdev.org/statustop.xpi";
T++;

e[T] = new extension("StumbleUpon");
e[T].id = "stumbleupon";
e[T].author = ["Geoff Smith"];
e[T].authorEmail = [""];
e[T].shortdesc = "'Stumble upon' websites recommended by a community";
e[T].description = "<p>Lets you 'stumble upon' cool websites that have been highlyrecommended (rated Great!) by friends and community members withinterests similar to your own.</p>";
e[T].homepage = "http://www.stumbleupon.com/";
e[T].version = "1.76";
e[T].updated = "";
e[T].size = "58";
e[T].installFile = "http://www.stumbleupon.com/stumbleupon.xpi";
T++;

e[T] = new extension("SuperScroll");
e[T].id = "superscroll";
e[T].author = ["Michael O'Rourke"];
e[T].authorEmail = ["momokatte@hotmail.com"];
e[T].shortdesc = "Configure smooth scrolling";
e[T].description = "<p>Configure smoothscrolling through the options window and change the scroll amount for directional keys.</p>";
e[T].homepage = "http://www.cosmicat.com/software/superscroll/";
e[T].version = "1.0";
e[T].updated = "";
e[T].size = "3.7";
e[T].installFile = "http://www.cosmicat.com/software/superscroll/superscroll.xpi";
T++;

e[T] = new extension("Tab Scroller");
e[T].id = "tabscroller";
e[T].author = ["Jochen"];
e[T].authorEmail = ["joe@krickelkrackel.de"];
e[T].shortdesc = "Switch between tabs using the mouse wheel (aka mouse rocker)";
e[T].description = "<p>This extension allows you to hold down the right mouse button and then use the scroll wheelto switch browser tab. In order to test it, you need to have at least two tabs opened in thecurrent window.  Also known as mouse rocker.</p>";
e[T].homepage = "http://www.krickelkrackel.de/tabscroller.htm";
e[T].version = "0.3.2";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://www.krickelkrackel.de/tabscroller.xpi";
T++;

e[T] = new extension("Tabbrowser Extensions");
e[T].id = "tbe";
e[T].author = ["Shimoda Hiroshi"];
e[T].authorEmail = ["piro@p.club.ne.jp"];
e[T].shortdesc = "Add-on for extending operations of tabbed browsing";
e[T].description = "<p>Add-on package for extending operations of tabbed browsing,e.g., tabs become re-ordable by drag and drop.</p>";
e[T].homepage = "http://white.sakura.ne.jp/~piro/xul/_tabextensions.html.en";
e[T].version = "1.8";
e[T].updated = "";
e[T].size = "176";
e[T].installFile = "http://white.sakura.ne.jp/~piro/xul/xpi/tabextensions_en.xpi";
T++;

e[T] = new extension("Tabbrowser Preferences");
e[T].id = "tabprefs";
e[T].author = ["Chris Cook"];
e[T].authorEmail = ["tangent@intraplanar.net"];
e[T].shortdesc = "Adds GUI options to change some of the hidden tab browser preferences";
e[T].description = "<p>This extension adds GUI options to change some of the hiddentab browser preferences available in Firebird. It also enables\"single window mode\" by opening links in a new tab instead of anew window.</p>";
e[T].homepage = "http://www.intraplanar.net/projects/tabprefs/";
e[T].version = "0.4";
e[T].updated = "";
e[T].size = "10";
e[T].installFile = "http://extensionroom.mozdev.org/install.php/http://www.intraplanar.net/projects/tabprefs/tabprefs_0.4.xpi";
T++;

e[T] = new extension("Tagzilla");
e[T].id = "tagzilla";
e[T].author = ["David Perry"];
e[T].authorEmail = [""];
e[T].shortdesc = "Easily add a tagline, random or specifically chosen by you";
e[T].description = "<p>Lets you add a tagline, random or specifically chosen by you,to the clipboard, textarea, end of an email, or newsgroup posting.</p>";
e[T].homepage = "http://tagzilla.mozdev.org/";
e[T].version = "0.049";
e[T].updated = "";
e[T].size = "78";
e[T].installFile = "http://downloads.mozdev.org/tagzilla/tagzilla-0.049.xpi";
T++;

e[T] = new extension("Text Links");
e[T].id = "textlinks";
e[T].author = ["Ted Mielczarek"];
e[T].authorEmail = ["luser_mozilla@perilith.com"];
e[T].shortdesc = "Treats selected plain text urls as links, right click to open.";
e[T].description = "<p>Treats selected plain text urls, h[anything]p and f[anything]p aslinks, right click to open.</p>";
e[T].homepage = "http://ted.mielczarek.org/code/mozilla/";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://ted.mielczarek.org/code/mozilla/textlink.xpi";
T++;

e[T] = new extension("Text / Plain");
e[T].id = "textplain";
e[T].author = ["Gilles Durys"];
e[T].authorEmail = ["mozbug@durys.net"];
e[T].shortdesc = "Adds context options for plain text urls and email";
e[T].description = "<p>Treats selected plain text urls, and email addresses aslinks and adds options to the context menu on how to use these.</p>";
e[T].homepage = "http://mozilla.durys.net/textplain/";
e[T].version = "0.3.2";
e[T].updated = "";
e[T].size = "7";
e[T].installFile = "http://mozilla.durys.net/textplain/textplain.xpi";
T++;

e[T] = new extension("Text Zoom");
e[T].id = "textzoom";
e[T].author = ["Michael O'Rourke"];
e[T].authorEmail = ["momokatte@hotmail.com"];
e[T].shortdesc = "This extension allows you to override the default text-zoom level in Mozilla Firebird.";
e[T].description = "<p>This extension allows you to override the default text-zoom level in Mozilla Firebird.</p>";
e[T].homepage = "http://www.cosmicat.com/software/textzoom/";
e[T].version = "1.0.01";
e[T].updated = "";
e[T].size = "4";
e[T].installFile = "http://www.cosmicat.com/software/textzoom/textzoom.xpi";
T++;

e[T] = new extension("Themer");
e[T].id = "themer";
e[T].author = ["Chris Neale"];
e[T].authorEmail = ["cdn@mozdev.org"];
e[T].shortdesc = "Provides a button that allows installation of downloaded .jar packaged themes";
e[T].description = "<p>Themer provides a button in the Themes section of Preferences(Options on recent Firebird nightlies) allowing installation of.jar packaged themes previously downloaded from a website.</p>";
e[T].homepage = "http://cdn.mozdev.org/themer/";
e[T].version = "mar-19";
e[T].updated = "";
e[T].size = "12";
e[T].installFile = "http://downloads.mozdev.org/cdn/themer/themer.xpi";
T++;

e[T] = new extension("Things They Left Out");
e[T].id = "ttlo";
e[T].author = ["!cdn"];
e[T].authorEmail = [""];
e[T].shortdesc = "Options panel for configuring your browser";
e[T].description = "<p>\"More Options\" appears under the tools menu.  There are panels forLanguages, MIME-types, security certificates, http, locale, debugging,and networking.  You are also able to configure favicons, image resizing, smooth scrolling, and Find as you Type.</p>";
e[T].homepage = "";
e[T].version = "0.1.4.1b";
e[T].updated = "";
e[T].size = "54";
e[T].installFile = "http://downloads.mozdev.org/flibble/ttlo2.xpi";
T++;

e[T] = new extension("This Window");
e[T].id = "thiswindow";
e[T].author = ["Ralph Churchill"];
e[T].authorEmail = ["churchillrm@cox.net"];
e[T].shortdesc = "Adds the ability to force a link to open in the current window";
e[T].description = "<p>A pretty trivial extension that adds the ability to force a windowto open in the current window. This is helpful if you don't want toopen another browser window.</p>";
e[T].homepage = "http://members.cox.net/churchillrm/install.html";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "2";
e[T].installFile = "http://downloads.mozdev.org/extensionroom/extensions/thiswindow/thiswindow.xpi";
T++;

e[T] = new extension("Tipbar");
e[T].id = "tipbar";
e[T].author = ["Rich Klein"];
e[T].authorEmail = ["richwklein@mchsi.com"];
e[T].shortdesc = "Adds a bar to the bottom of the content window that shows Tips.";
e[T].description = "<p>Adds a bar to the bottom of the content window that shows Tips.</p>";
e[T].homepage = "http://tipbar.mozdev.org/";
e[T].version = "0.5.0";
e[T].updated = "";
e[T].size = "9";
e[T].installFile = "http://downloads.mozdev.org/tipbar/tipbar050.xpi";
T++;

e[T] = new extension("Trivial");
e[T].id = "trivial";
e[T].author = ["Chris Neale"];
e[T].authorEmail = ["cdn@mozdev.org"];
e[T].shortdesc = "Adds buttons for Cut, Copy, Paste, Full Screen, Tab/Window Close, and Save Page!";
e[T].description = "<p>Trivial adds the following toolbar buttons for Firebird: Cut,Copy, Paste, Toggle Full Screen, Close Tab, Close Window, andSave Page, and enhances the Print button by allowing you tochoose Print Preview from its context menu.</p><p>It also adds a New Tab button to the left hand end of the tab bar.</p>";
e[T].homepage = "http://cdn.mozdev.org/trivial/";
e[T].version = "apr-17";
e[T].updated = "";
e[T].size = "22";
e[T].installFile = "http://downloads.mozdev.org/cdn/trivial/trivial.xpi";
T++;

e[T] = new extension("URLfix");
e[T].id = "urlfix";
e[T].author = ["Sergey Chernyshev"];
e[T].authorEmail = ["urlfix.mozdev.org@antispam.drouk.ru"];
e[T].shortdesc = "URLFix automatically converts URLs, entered using wrong keyboard    layout (cyrillic for example).";
e[T].description = "<p>Everybody using multilingual computer has to switch between keyboard layouts (usually two of them). Periodically this causes absolutely everyone to forget to switch layout before typing a URL into the browser's URL bar.</p><p>If URL entered contains only localized symbols then we can easily convert it to latin symbols using customizable keyboard layouts map.</p><p>Configuring URLFix is very easy - all you have to do is to enter sequences of characters - \"Convert from:\" sequence has all localized characters and \"Convert to:\" sequence contains all corresponding latin characters.</p>";
e[T].homepage = "http://www.mozdev.ru/twiki/bin/view/Mozdev/UrlFix";
e[T].version = "0.1.0.2";
e[T].updated = "";
e[T].size = "6";
e[T].installFile = "http://downloads.mozdev.org/urlfix/urlfix.xpi";
T++;

e[T] = new extension("User Agent Switcher");
e[T].id = "useragentswitcher";
e[T].author = ["Chris Pederick"];
e[T].authorEmail = [""];
e[T].shortdesc = "Easily control the browser's User Agent string from the Tools menu";
e[T].description = "<p>This extension adds a menu to switch the user agent of the browser. It is designed to providefunctionality similar to the \"Browser Identification\" feature of Opera and allows you to configure the list of user agents to display in the menu.</p>";
e[T].homepage = "http://chrispederick.myacen.com/work/firebird/useragentswitcher/";
e[T].version = "0.3";
e[T].updated = "";
e[T].size = "6.4";
e[T].installFile = "http://chrispederick.myacen.com/work/firebird/useragentswitcher/useragentswitcher.xpi";
T++;

e[T] = new extension("User Agent Toolbar Widget");
e[T].id = "uawidget";
e[T].author = ["David Illsley"];
e[T].authorEmail = ["illsleydc@bigfoot.com"];
e[T].shortdesc = "Easily control the browser's User Agent string from the toolbars";
e[T].description = "<p>The User Agent Toolbar as an extension which allows you to modify the useragent string whichmozilla sends to servers and which is provided to Javascript/ECMAscript through navigator.userAgent.</p>";
e[T].homepage = "http://uabar.mozdev.org/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "15";
e[T].installFile = "http://uabar.mozdev.org/uawidget.xpi";
T++;

e[T] = new extension("Venkman");
e[T].id = "venkman";
e[T].author = ["Robert Ginda"];
e[T].authorEmail = [""];
e[T].shortdesc = "Outstanding JavaScript debugger";
e[T].description = "<p>Venkman is the outstanding JavaScript debugger for the Mozilla Application Suite.</p><p>It also works for Firebird, but was not designed for it and so has a few quirks:</p><ul>  <li>It won't show up in the Extensions panel of the Options window.</li>  <li>It will not add any items to Firebird's menus for you to run it.  Instead you must  run it from the command line by running Firebird with the <kbd>-venkman</kbd> or  <kbd>-chrome chrome://venkman/content/</kbd> parameter.  Typing <kbd>chrome://venkman/content/</kbd>  in the url bar might also work (though that will load the debugger within the browser window).</li></ul><p>Some good documentation on using Venkman can be found at <a href=\"http://devedge.netscape.com/viewsource/2002/venkman/01\">Netscape DevEdge</a>.";
e[T].homepage = "http://www.hacksrus.com/~ginda/venkman/";
e[T].version = "0.9.7.0";
e[T].updated = "";
e[T].size = "273";
e[T].installFile = "http://www.hacksrus.com/~ginda/venkman/venkman-0.9.70.xpi";
T++;

e[T] = new extension("Web Developer");
e[T].id = "webdeveloper";
e[T].author = ["Chris Pederick"];
e[T].authorEmail = [""];
e[T].shortdesc = "Adds a menu and toolbar of web devloper tools";
e[T].description = "<p>Adds a menu and a toolbar to the browser with various web developer tools. Current tools include converting form POSTs to GETs, hiding images, outlining block level elements, and disabling styles - plus many more.</p>";
e[T].homepage = "http://chrispederick.myacen.com/work/firebird/webdeveloper/";
e[T].version = "0.4";
e[T].updated = "";
e[T].size = "25";
e[T].installFile = "http://chrispederick.myacen.com/work/firebird/webdeveloper/webdeveloper.xpi";
T++;

e[T] = new extension("Webpanel Enhancer");
e[T].id = "webpanelenhancer";
e[T].author = ["Pascal Guimier"];
e[T].authorEmail = ["talou@timot.net"];
e[T].shortdesc = "Adds some features to Firebird's Webpanel tool.";
e[T].description = "<p>The \"Webpanel enhancer\" extension allows you to grab a link, a page or a HTML source into the sidebar for a temporary glimpse. It tries to recover the Page Holder tool appeared in august 3rd. and 4th. nightly builds.</p>";
e[T].homepage = "http://editcss.mozdev.org/indexwpe.html";
e[T].version = "0.01.1";
e[T].updated = "";
e[T].size = "5";
e[T].installFile = "http://downloads.mozdev.org/editcss/wpe.xpi";
T++;

e[T] = new extension("Window Layers for Windows");
e[T].id = "windowlayers";
e[T].author = ["Daniel Matejka"];
e[T].authorEmail = ["danm-moz@comcast.net"];
e[T].shortdesc = "A toolbar button (in Mozilla, a statusbar icon) which allows the user to place windows in layers.";
e[T].description = "<p>A toolbar button (in Mozilla, a statusbar icon) which allows the userto place windows in layers. Layers are vertical stacking groups intowhich a window can be restricted, so a window in a lower layer can neverbe moved in front of a window in a higher layer. Barring bugs, that is.A window can also be pinned to the desktop, below all otherapplications. This extension works best on Windows and not at all onLinux (sorry, but that's the state of the underlying widget code).</p>";
e[T].homepage = "http://home.comcast.net/%7Edanm-moz/winlayers/";
e[T].version = "1.5.1";
e[T].updated = "";
e[T].size = "12";
e[T].installFile = "http://home.comcast.net/%7Edanm-moz/winlayers/winlayers.xpi";
T++;

e[T] = new extension("Work Offline");
e[T].id = "workoffline";
e[T].author = ["Pike"];
e[T].authorEmail = ["pike@pikey.me.uk"];
e[T].shortdesc = "Enables/disables Work Offline via a menu option, the setting is remembered between sessions.";
e[T].description = "<p>Enables/disables Work Offline via a menu option, the setting is remembered between sessions.</p>";
e[T].homepage = "http://www.pikey.me.uk/mozilla/#wo";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "3";
e[T].installFile = "http://www.pikey.me.uk/mozilla/extensions/workoffline.xpi";
T++;

e[T] = new extension("x");
e[T].id = "x";
e[T].author = ["Stephen Clavering", "Chris Neale"];
e[T].authorEmail = ["mozilla@clav.me.uk", "cdn@mozdev.org"];
e[T].shortdesc = "Quickly clear privacy-related data";
e[T].description = "<p>x adds a toolbar button from which you can quickly clear privacy sensitive data,specifically: history, form info, saved passwords, download history, cookies, andthe cache (both disk and in memory cache).</p><p>Clicking the button gives you a dialogue window from which you can select whichdata you want clearing.</p>";
e[T].homepage = "http://cdn.mozdev.org/";
e[T].version = "0.2";
e[T].updated = "";
e[T].size = "9";
e[T].installFile = "http://downloads.mozdev.org/cdn/x/x.xpi";
T++;

e[T] = new extension("xKiosk");
e[T].id = "xkiosk";
e[T].author = ["Stephen Clavering", "Chris Neale"];
e[T].authorEmail = ["mozilla@clav.me.uk", "cdn@mozdev.org"];
e[T].shortdesc = "Quickly clear privacy-related data";
e[T].description = "<p>xKiosk adds a toolbar button from which you can quickly clear privacy sensitivedata, specifically: history, form info, saved passwords, download history, cookies,and the cache (both disk and in memory cache).</p><p>When you click the button you are asked to confirm the action, after which all thedata is cleared.  It is expected that this could be useful in web kiosks (hence thename).</p>";
e[T].homepage = "http://cdn.mozdev.org/";
e[T].version = "0.1";
e[T].updated = "";
e[T].size = "8";
e[T].installFile = "http://downloads.mozdev.org/cdn/x/xkiosk.xpi";
T++;

extensionArray = extensions;
